

POST http://localhost:3000/courses
Content-Type: application/json

{
    "name": "Curso de Docker"
}

### 

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/62b2de70-5031-4522-bf41-3b8f823ad1fd